# Dependabot configuration optimized for infrequent production deployments
# Focus on security updates and major releases only

version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Vilnius"
    # Only security and major Laravel updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      security:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      laravel-major:
        patterns:
          - "laravel/*"
        update-types:
          - "major"
          - "minor"
    open-pull-requests-limit: 3

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "tuesday"
      time: "09:00"
      timezone: "Europe/Vilnius"
    # Only security updates for frontend
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
    groups:
      security:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 2

  - package-ecosystem: "docker"
    directory: "/docker/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Vilnius"
    open-pull-requests-limit: 1
